spring:
  profiles:
    active: local  # default
    group:
      local:
        - common
        - security
      prod:
        - common
        - security

---
spring:
  config:
    activate:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${SPRING-DATASOURCE-URL}
    username: ${SPRING-DATASOURCE-USERNAME}
    password: ${SPRING-DATASOURCE-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate.default_batch_fetch_size: 100
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SRPING-DATASOURCE-URL}
    username: ${SPRING-DATASOURCE-USERNAME}
    password: ${SPRING-DATASOURCE-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring:
  config:
    activate:
      on-profile: security

security:
  jwt:
    secret-key: ${SECRET-KEY}
    expired-time-ms: ${EXPIRED-TIME-MS}